"""sensor_readings

Revision ID: 2357a17d9c63
Revises: efaf95186a8d
Create Date: 2026-10-03 10:44:40.192392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2357a17d9c63'
down_revision: Union[str, Sequence[str], None] = 'efaf95186a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_id_recorded_at', 'sensor_readings', ['device_id', 'recorded_at'], unique=False)
    op.add_column('devices', sa.Column('sampling_interval_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False))
    op.add_column('devices', sa.Column('tracking_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # Backfill sampling_interval_seconds from default_config for devices that
    # already stored it there (Phase 2); devices without it keep the server
    # default of 300. After this migration, the column is the source of truth.
    op.execute(
        sa.text(
            """
            UPDATE devices
            SET sampling_interval_seconds = (default_config->>'sampling_interval_seconds')::int
            WHERE default_config ? 'sampling_interval_seconds'
              AND (default_config->>'sampling_interval_seconds') ~ '^[0-9]+$'
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'tracking_enabled')
    op.drop_column('devices', 'sampling_interval_seconds')
    op.drop_index('ix_sensor_readings_device_id_recorded_at', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
